### ISSUE TITLE
Received message larger than max (8400136 vs. 4194304)

### ISSUE THREAD

**Issue by Mrtenz** [Alethio/eth2stats-client#17]
Sometimes the client crashes and on restart it keeps crashing with the following error message:

```
time="2020-02-10T15:42:17Z" level=error msg="[prysm] rpc error: code = ResourceExhausted desc = grpc: received message larger than max (8400136 vs. 4194304)"
time="2020-02-10T15:42:17Z" level=fatal msg="[telemetry] rpc error: code = ResourceExhausted desc = grpc: received message larger than max (8400136 vs. 4194304)"
```

This wasn't an issue before and I cannot seem to reproduce it consistently. I'm running the client as part of a `docker-compose` stack, together with the Prysm beacon node:

```yml
version: '2'

services:
  node:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    restart: always
    stdin_open: true
    tty: true
    command: --datadir=/data --p2p-host-ip=94.103.153.169 --min-sync-peers=7 --p2p-max-peers=100 --deposit-contract=0x4689a3C63CE249355C8a573B5974db21D2d1b8Ef
    ports:
     - 4000:4000
     - 13000:13000
    volumes:
     - '/opt/prysm/beacon:/data'
    labels:
     - 'com.centurylinklabs.watchtower.enable=true'
     
  ethstats:
    image: alethio/eth2stats-client:latest
    restart: always
    command: run --v --eth2stats.node-name="morten.eth" --data.folder="/data" --eth2stats.addr="grpc.sapphire.eth2stats.io:443" --eth2stats.tls=true --beacon.type="prysm" --beacon.addr="node:4000" --beacon.metrics-addr="http://node:8080/metrics"
    volumes:
     - '/opt/prysm/stats:/data'
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    depends_on:
     - node
    links:
     - node:node

  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --label-enable --cleanup --include-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
