### ISSUE TITLE
fatal error: invalid node URL: "beacon:4000"

### ISSUE THREAD

**Issue by mgcrea** [Alethio/eth2stats-client#52]
Not sure if I'm missing something but trying to run the eth2stats client inside a docker-compose along a working beacon (reachable at `beacon:4000`), I end up with the following error on startup:

```
prysm_eth2stats | time="2020-08-17T09:02:05Z" level=info msg="Could not load config file. Falling back to args. Error: Config File \"config\" Not Found in \"[/]\"" module=main
prysm_eth2stats | time="2020-08-17T09:02:05Z" level=fatal msg="[core] invalid node URL: \"beacon:4000\""
```

Compose block:

```
  stats:
    image: alethio/eth2stats-client:latest
    restart: always
    container_name: prysm_eth2stats
    hostname: prysm_eth2stats
    environment:
      - TZ=${TZ}
    volumes:
      - "./volumes/eth2stats/data:/data:rw"
    command:
      - run
      - --eth2stats.node-name="mgcrea-prysm-01"
      - --data.folder="/data"
      - --eth2stats.addr="grpc.medalla.eth2stats.io:443"
      - --eth2stats.tls=true
      - --beacon.type="prysm"
      - --beacon.addr="beacon:4000"
      - --beacon.metrics-addr="http://beacon:8080/metrics"
    depends_on:
      - beacon
```

**Comment by mgcrea** [comment]
Issue is that the CLI parser does not support the (maybe escaped by compose) double quotes: `"`.

This does work.

```yaml
stats:
    image: alethio/eth2stats-client:latest
    restart: always
    container_name: prysm_eth2stats
    hostname: prysm_eth2stats
    environment:
      - TZ=${TZ}
    volumes:
      - "./volumes/eth2stats/data:/data:rw"
    command:
      - run
      - --eth2stats.node-name=mgcrea-prysm-01
      - --data.folder=/data
      - --eth2stats.addr=grpc.medalla.eth2stats.io:443
      - --eth2stats.tls=true
      - --beacon.type=prysm
      - --beacon.addr=beacon:4000
      - --beacon.metrics-addr=http://beacon:8080/metrics
    depends_on:
      - beacon
```
